### ISSUE TITLE
[feature] Add an `Events` field to the transaction

### ISSUE THREAD

**Issue by jinoosss** [gnolang/tx-indexer#42]
# Description

https://github.com/gnolang/gno/pull/1653 as a change, 
adds data to the Events field in the transaction result.

Add functionality to tx-indexer to handle events data.
The tx-indexer should be able to filter and verify the data in events.

**Comment by jinoosss** [comment]
Hi @zivkovicmilos @ajnavarro ,
I'd love to hear your thoughts on this feature.

Is it enough to just add the Events field to transaction filters and models only?
Or would it be better to add Event related queries as well ?

**Comment by ajnavarro** [comment]
Hi @jinoosss . What you did adding `Events` to transactions looks like the way to go for me.

**Comment by jinoosss** [comment]
Hi @ajnavarro ,
I apologize, I'm late.

I've updated the relevant PR. 

If you don't mind, could you please review this PR? #43
